config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  # Etablecemos las rutas clasicas para el controlador intervals new y create
  resources :intervals, only: %i[new create]
  # Establecemos nuestra nuta '/' como la vista del new
  root "intervals#new"
  # Creamos una ruta para mostrar los resultados, tambien podia haber sido un show
  get "/result", to: "intervals#result"
  # Creamos una ruta que es invocada y responde el método again de intervals
  # controller y funciona para volver a probar la calculadora
  get "/again", to: "intervals#again"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/interval.rb
class Interval < ApplicationRecord
  # Validaciones para los atributos minimum y maximum de la instancia de interval
  validates :minimum, presence: { message: 'no puede estar en blanco' }
  validates :maximum, presence: { message: 'no puede estar en blanco' }
  validates :minimum, numericality: { greater_than: 0, message: 'debe ser mayor que 0' }
  validates :maximum, numericality: { greater_than: :minimum, message: 'debe ser mayor que el mínimo' }, if: -> { self.minimum.present? }
  # Despues de validar activamos este callback que crea el atributo results basado en los atributos
  # minimum y maximum
  after_validation :determinar_naturales

  # Este método de clase contiene la lógica del ejericio
  def determinar_naturales
    (self.minimum..self.maximum).each do |numero|
      suma_divisores = 0
      (1..numero / 2).each do |i|
        suma_divisores += i if (numero % i).zero?
      end
      self.results.push(numero) if suma_divisores == numero
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/intervals_controller.rb
class IntervalsController < ApplicationController
  # Desactivamos la protección del token de veriricación para poder hacer peticiones
  # con curl o con Postman, pero en entornos de producción debe eliminarse obligatoriamente
  # y realizar las peticiones sacando el token del navegador y agregandolo al header de la
  # petición
  skip_before_action :verify_authenticity_token

  # Definimos una nueva instancia de Interval para captar los datos en el form
  # que se encuentra en la vista correspondiente al método (new.html.erb)
  def new
    @interval = Interval.new
  end

  # Creamos la instancia de interval recibiendo los params pasados desde el form
  # y filtrados por el método de seguridad interval_params
  # luego explicamos el comportamiento de la petición al método create dependiendo
  # del formato requerido, HTML o JSON
  def create
    @interval = Interval.new(interval_params)
    respond_to do |format|
      if @interval.save
        format.html { redirect_to result_path }
        format.json { render json: @interval.to_json(only: %i[minimum maximum results]), status: 200 }
      else
        puts @interval.errors.full_messages
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @interval.errors, status: :unprocessable_entity }
      end
    end
  end

  # Metodo usado para la vista correspondiendo mostrar los resultados del interval
  # acabado de crear
  def result
    @interval = Interval.last
  end

  # Este método es invocado cuando se da en el botón de probar de nuevo, se deja
  # comentado la linea 41 en caso de requerir persistencia o no de la información
  def again
    # Interval.destroy_all

    respond_to do |format|
      format.html { redirect_to new_interval_path }
      format.json { head :no_content }
    end
  end

  private

  # Metodo privado para permitir pasar parámetros desde un form
  def interval_params
    params.require(:interval).permit(:minimum, :maximum)
  end
end
## NT-2

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/intervals_helper.rb
module IntervalsHelper
end

app/views/intervals/new.html.erb
<%# Esta vista está asociada al método new de intervals controller y es
donde vemos el form para establecer minimum y maximum %>
<div class="container w-75 text-center">
  <%= simple_form_for @interval do |f|%>
    <%= f.input :minimum, label: "Mínimo", input_html: { style: "background: rgba(255,255,255,0.3); color: white;" }%>
    <%= f.input :maximum, label: "Máximo", input_html: { style: "background: rgba(255,255,255,0.3); color: white;" } %>
    <%= f.submit "Calcular", class: "btn btn-primary"%>
  <% end %>
</div>

app/views/intervals/result.html.erb
<%# Esta es la vista asociada al método result del intervals
controller y muesra los resultados y permite probar de nuevo%>
<div class="container w-75 text-center">
  <h6>Los numeros naturales perfectos que hay en el rango del <%= @interval.minimum %> al <%= @interval.maximum %> son <%= @interval.results.length %> y son:</h2>
  <ul class="list-unstyled">
    <% @interval.results.each do |result| %>
      <li><%= result %></li>
    <% end %>
  </ul>
  <%= link_to 'Probar de nuevo', again_path, class: "btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaturalesPerfectos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style="background-size: cover; background-repeat: no-repeat; background-image: url('https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'); min-height: 100vh;" class="d-flex flex-column align-items-center justify-content-center text-light">
    <div class="rounded mb-3"><h2 class="shadow" style="background-color: rgba(0,0,0,0.8)">Calculadora de números naturales perfectos</h2></div>
    <div class="w-25 border b-white rounded p-4" style="background: transparent; backdrop-filter: blur(10px);">
      <%= yield %>
    </div>
    <div class="shadow mt-3" style="background-color: rgba(0,0,0,0.9)">App hecha con <i class="fa-solid fa-heart text-danger"></i></div>
  </body>
</html>